create table dbo.BetList
(
    Id          bigint                                     not null,
    SportName   varchar(1000),
    SportId     int,
    LeagueName  varchar(1000),
    LeagueId    int,
    Home        varchar(1000),
    Away        varchar(1000),
    EventId     int,
    MarketName  varchar(1000),
    SideName  varchar(1000),
    Points      decimal(9, 5),
    EventTime   datetimeoffset(0),
    Status      varchar(1000),
    WinLoss     decimal(9, 5),
    Price       decimal(9, 5),
    Stake       decimal(9, 5),
    BetTypeId   int,
    BetTime     datetimeoffset(0),
    WinLoseDate datetimeoffset(0),
    CreatedAt   datetimeoffset(0) default sysdatetimeoffset() not null,
    UpdatedAt   datetimeoffset(0) default sysdatetimeoffset() not null,
    constraint PK_BetList primary key (Id),
)
create type BetListType as table
(
    Id          bigint not null,
    SportName   varchar(1000),
    SportId     int,
    LeagueName  varchar(1000),
    LeagueId    int,
    Home        varchar(1000),
    Away        varchar(1000),
    EventId     int,
    MarketName  varchar(1000),
    SideName  varchar(1000),
    Points      decimal(9, 5),
    EventTime   datetimeoffset(0),
    Status      varchar(1000),
    WinLoss     decimal(9, 5),
    Price       decimal(9, 5),
    Stake       decimal(9, 5),
    BetTypeId   int,
    BetTime     datetimeoffset(0),
    WinLoseDate datetimeoffset(0),
    primary key (Id)
)